# NOTE: Use Azure Key Vault + CSI driver in production
apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
  namespace: user-api
type: Opaque
data:
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
