apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: order-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "order-db-svc"
  DB_PORT: "27017"
  DB_NAME: "ordersdb"
