apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-api-config
  namespace: inventory-api
data:
  DB_HOST: "inventory-db-svc"
  DB_PORT: "5432"
  DB_NAME: "inventorydb"
  SPRING_PROFILES_ACTIVE: "production"
