# NOTE: Use Azure Key Vault + CSI driver or External Secrets Operator in production
apiVersion: v1
kind: Secret
metadata:
  name: inventory-api-secret
  namespace: inventory-api
type: Opaque
data:
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
