apiVersion: v1
kind: Service
metadata:
  name: inventory-api-svc
  namespace: inventory-api
spec:
  selector:
    app: inventory-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db-svc
  namespace: inventory-api
spec:
  selector:
    app: inventory-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
